### PR TITLE
chore: update .env.example

### PR DESCRIPTION
**Pull request by Ssttar**

### CODE REVIEW

**Comment by wibus-wee** [comment]
Why?

If unblock is deployed remotely, and if the host is not set to 0.0.0.0, you will not be able to access unblock directly through ip locally.

**Comment by Ssttar** [comment]
ops..I misunderstand,sorry

**Review by wibus-wee — CHANGES_REQUESTED** [review]
What does this modify in the last line?

**Comment by Ssttar** [comment]
emmmm,no modification

**Comment by wibus-wee** [comment]
So to me this doesn't seem like much of a modification, maybe I need to turn off the pr.

Thank you for your contribution!

**Pull request closed without merging**
