### PR TITLE
fix for extension download

### PR DESCRIPTION
**Pull request by ImSingee**
### Description

This fixes the extension download feature again…

### Linked Issues
 #26

### Additional context

This uses ofetch.native to make response status code and headers correct.

### CODE REVIEW

**Review by wibus-wee — APPROVED** [review]

**Comment by jjaychen1e** [comment]
@ImSingee this will cause the failure of extension search, not sure why:

image

```
Reason: HTTP response received with error
Domain: network
Time: 10:12:17.875
Service: Internal networking engine
Underlying: 
	Domain: NSURLErrorDomain -1015
	_NSURLErrorRelatedURLSessionTaskErrorKey: (
    "LocalDataTask <3883A677-6D75-46F0-B32A-1EF646E8BBDD>.<178>"
)
	NSLocalizedDescription: cannot decode raw data
	NSErrorFailingURLKey: https://backend.raycast.com/api/v1/extensions/trending?page=1&per_page=3&include_native=true
	NSErrorFailingURLStringKey: https://backend.raycast.com/api/v1/extensions/trending?page=1&per_page=3&include_native=true
	NSUnderlyingError: 
		Domain: kCFErrorDomainCFNetwork -1015
		NSErrorPeerAddressKey: {length = 16, bytes = 0x100223837f0000010000000000000000}
	_NSURLErrorFailingURLSessionTaskErrorKey: LocalDataTask <3883A677-6D75-46F0-B32A-1EF646E8BBDD>.<178>
```

I'm deploying the service on a server and use NGINX as reverse proxy.

The result is correct since I have used Proxyman to capture the response and verified the result. And curl also returns the response successfully.

But directly open the url on both Safari and Chrome will also fail. In Chrome I get an error: `ERR_CONTENT_DECODING_FAILED`.

**Comment by ImSingee** [comment]
@jjaychen1e Maybe check your server network or nginx settings? I use Caddy and it works well.

image

**Comment by jjaychen1e** [comment]
> @jjaychen1e Maybe check your server network or nginx settings? I use Caddy and it works well.
> 
> image

It seems NGINX doesn't support Brotli encoding (which is used by the store related APIs), so I'm getting the error. It's expensive to enable Brotli with NGINX, I'm going to use Caddy instead. Thank you!

**Comment by jjaychen1e** [comment]
@ImSingee My guess was wrong. I tried Caddy, and tried deploy the service on my Mac directly, they behave the same.

All Safari, Chrome, Postman fails to decode the data.

Only curl and Proxyman can read the response.

Do you have additional setups that may impact the result?

**Comment by ImSingee** [comment]
@jjaychen1e So interesting.

Would you mind trying my server for a test? https://singee.link/raycast-unlock.sgmodule

Turn off Cloud Sync before try if you don't want to leak your settings to me.

**Comment by jjaychen1e** [comment]
> @jjaychen1e So interesting.
> 
> Would you mind trying my server for a test? https://singee.link/raycast-unlock.sgmodule
> 
> Turn off Cloud Sync before try if you don't want to leak your settings to me.

Don't worry, I just use one API to test the availability.

---

It's really wired it works on your server, I also tried your fork of this project.

When I use `http://127.0.0.1:3000/api/v1/store_listings/search?include_native=true&q=obsidian%20bookmarks&page=1&per_page=25`, all Safari, Chrome, and Postman fail to decode the data.

But when I use `https://https://raycast.singee.me/api/v1/store_listings/search?include_native=true&q=obsidian%20bookmarks&page=1&per_page=25` it works well.

Something related to encoding may happened in your Caddy config, so it works well in your server. Safari, Chrome and Postman all complain about the decoding.

When I manually remove the 'content-encoding' in the header, it works. It seems fastify does not compress the data according to the `content-encoding` field automatically.

I'm not familiar with node.js and fastify, here is how I try to remove the `content-encoding` setting in the header. (Directly use `reply.header` does not work)

```typescript
    const headers = Array.from(backendResponse.headers.entries())
    const headersRecord = Object.fromEntries(headers)

    const response = new Response(backendResponse.body, {
      status: 200,
      headers: {
        ...headersRecord,
        'content-encoding': '',
      },
    })
    Debug.info(`[GET] ${subUrl} <-- 托底策略 <-- Backend Response`)
    return reply.send(response)
  })
  ```

**Comment by ImSingee** [comment]
@jjaychen1e Oh yes you are right, the code is incorrect because of something.

I tried `http://10.104.0.2:9801/api/v1/store_listings/search?include_native=true&q=obsidian%20bookmarks&page=1&per_page=25
` (direct) and `http://raycast.test/api/v1/store_listings/search?include_native=true&q=obsidian%20bookmarks&page=1&per_page=25` (via caddy), and both of these can not work.

The reason that my server works is that I put my server behind Cloudflare.

BTW, please remove my server address from the issue since I don't want it to be public.

**Comment by jjaychen1e** [comment]
@ImSingee I've removed your server address.

BTW, we may need this: https://github.com/fastify/fastify-compress

**Comment by ImSingee** [comment]
@jjaychen1e I just submitted a PR based on your look. I'm not familiar with fastify, so I decided not to use fastlify-compress.

**Pull request merged**
